version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    # restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    networks:
      - starter-kit-network
    depends_on:
      - redis

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    # restart: unless-stopped
    tty: true
    ports:
      - "8070:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - starter-kit-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel-redis
    # restart: unless-stopped
    tty: true
    ports:
      - "6377:6379"
    networks:
      - starter-kit-network

networks:
  starter-kit-network:
    driver: bridge
