version: "3.7"
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel
        container_name: laravel
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/www/html
            - ../vendor:/var/www/vendor
            - ../node_modules:/var/www/node_modules

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8070:80"
        volumes:
            - ../:/var/www
            - ../nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - starter-kit-network

networks:
  starter-kit-network:
    driver: bridge